### ISSUE TITLE
rcutils_concat() should use an allocator

### ISSUE THREAD

**Issue by sloretz** [ros2/rcutils#103]
`rcutils_concat()` currently uses `malloc()` internally instead of an allocator.

https://github.com/ros2/rcutils/blob/9092a2581aba9be2a44f90a646e75f8d129ccdfa/src/concat.c#L40

**Comment by mikaelarguedas** [comment]
:+1: 
Apparently the issue tracking that has been closed https://github.com/ros2/rcutils/issues/4

**Comment by wjwwood** [comment]
Concat was removed in https://github.com/ros2/rcutils/pull/102
