### ISSUE TITLE
try out awesome reusable visibility macro

### ISSUE THREAD

**Issue by mikaelarguedas** [ros2/rcutils#11]
see https://github.com/ros2/examples/pull/149

**Comment by mikaelarguedas** [comment]
explore what CMAKE can do for us to simplify this

**Comment by mikaelarguedas** [comment]
needs to be tested on some packages before propagating the use of this to most of the stack

**Comment by clalancette** [comment]
I think it is pretty clear we aren't going to go this direction, so I'm going to close this issue out.
