### ISSUE TITLE
File size of dummy.dummy.txt on windows might be 5 or 6 bytes

### ISSUE THREAD

**Issue by brawner** [ros2/rcutils#198]
In PR #197, the `TestFilesystemFixture.calculate_file_size` test checks the file size of a small text file containing the string "ROS2". Because of windows-style line-endings and how git automatically corrects them, this file is actually 6 bytes when checked out with git, but 5 bytes when directly downloaded from gist.

Example of test failure
https://citest.ros2.org/job/ci_windows/116/testReport/rcutils/TestFilesystemFixture/

**Comment by brawner** [comment]
@Karsten1987

**Comment by Karsten1987** [comment]
Thanks @brawner for reporting this. I somehow ignored to run tests for `rcutils` when introducing the change for rosbags. I'll work on a correction.
