### ISSUE TITLE
char_array is leaking memory

### ISSUE THREAD

**Issue by piraka9011** [ros2/rcutils#231]
The most recent ASAN builds for Linux are failing [nightly_linux_address_sanitizer#373](https://ci.ros2.org/view/nightly/job/nightly_linux_address_sanitizer/373).

Failing tests:

* [ArrayCharTest.vsprintf_fail](https://github.com/ros2/rcutils/blob/70d828c658410e790a811cd5db365606320c0faa/test/test_char_array.cpp#L100)
* [TestLoggingCustomEnv.test_logging](https://github.com/ros2/rcutils/blob/70d828c658410e790a811cd5db365606320c0faa/test/test_logging_custom_env.cpp#L31)

It looks like it's coming from [`rcutils_char_array_init`](https://github.com/ros2/rcutils/blob/a6306c65c34fecf6f91310ac9830b694a768fed7/src/char_array.c#L52) and [`rcutils_char_array_strncat`](https://github.com/ros2/rcutils/blob/a6306c65c34fecf6f91310ac9830b694a768fed7/src/char_array.c#L214)  in `src/char_array.c` .

## Proposed solution 

1. ?
2. Use `char_array->buffer_length` instead of `strlen(char_array->buffer)`.

**Comment by clalancette** [comment]
Yep, I see the problem.  We can't unilaterally assign to char->buffer on a realloc; if the realloc fails, we lose the pointer.  Patch upcoming.
