### ISSUE TITLE
log throttle tests are failing on macOS

### ISSUE THREAD

**Issue by wjwwood** [ros2/rcutils#27]
See: http://ci.ros2.org/job/nightly_osx_release/481/testReport/

These changes were merged yesterday: https://github.com/ros2/rcutils/pull/23

I don't have an example of these tests passing on the above link nightly (this is the first night), so I can't say if it is flakey or not. I assume so since I assume there was a passing CI job for macOS before merging. I don't see the same failure on Linux or Windows atm.

**Comment by dirk-thomas** [comment]
This was already mentioned yesterday: https://github.com/ros2/rclcpp/pull/333#issuecomment-306316157

See #28 for longer timeouts.

**Comment by wjwwood** [comment]
macOS release is back to green: http://ci.ros2.org/view/nightly/job/nightly_osx_release/482/
