### ISSUE TITLE
MSBuild warnings C5105: macro expansion producing 'defined' has undefined behavior

### ISSUE THREAD

**Issue by jacobperron** [ros2/rcutils#310]
Building the latest versions of Eloquent or Foxy from source produces several warnings on Windows with the following message:

    C5105: macro expansion producing 'defined' has undefined behavior

For example (foxy): [![Build Status](https://ci.ros2.org/buildStatus/icon?job=ci_windows&build=12993)](https://ci.ros2.org/job/ci_windows/12993/)

Seems to be coming from the following rcutils source files on the `foxy` branch:

- rcutils\src\filesystem.c
- rcutils\src\logging.c
- rcutils\src\process.c
- rcutils\src\shared_library.c
- rcutils\src\testing\fault_injection.c
- rcutils\src\time_win32.c

I have not observed the warning on Dashing or Rolling.

**Comment by clalancette** [comment]
Ah yeah, we probably need to backport #311 to fix that.

**Comment by clalancette** [comment]
I backported this to Foxy.  I'm not going to bother with Eloquent since this is the last sync, so I'll close this out.
