### ISSUE TITLE
add namespace to some existing functions

### ISSUE THREAD

**Issue by wjwwood** [ros2/rcutils#37]
For example (just the ones I've noticed):

- `cli_option_exist` should be `rcutils_cli_option_exist`
- `cli_get_option` should be `rcutils_cli_get_option`

That might be all of them, but those for sure.

**Comment by fmrico** [comment]
I can help with this

**Comment by wjwwood** [comment]
Thanks @fmrico, we're in the middle of a feature freeze for beta 2, so I'll probably have to wait to merge your changes in until after that. So, it will probably be a few weeks. I'll go ahead and review them and run CI if our farm isn't too busy.

**Comment by wjwwood** [comment]
Here is CI for your changes:

- Linux:
  - [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux&build=2839)](http://ci.ros2.org/job/ci_linux/2839/)
- Linux-aarch64:
  - [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux-aarch64&build=343)](http://ci.ros2.org/job/ci_linux-aarch64/343/)
- macOS:
  - [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_osx&build=2295)](http://ci.ros2.org/job/ci_osx/2295/)
- Windows:
  - [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_windows&build=2976)](http://ci.ros2.org/job/ci_windows/2976/)

As I said, it might be a while before we merge it though. Thanks for working on it!

**Comment by dirk-thomas** [comment]
@fmrico The code currently doesn't even compile. Can you please look into the compiler errors and update the patch(es). Thanks.

**Comment by fmrico** [comment]
@dirk-thomas I commited and pushed one pending change. May you try again?

**Comment by dirk-thomas** [comment]
- Linux:
  - [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux&build=2860)](http://ci.ros2.org/job/ci_linux/2860/)
- Linux-aarch64:
  - [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux-aarch64&build=364)](http://ci.ros2.org/job/ci_linux-aarch64/364/)
- macOS:
  - [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_osx&build=2315)](http://ci.ros2.org/job/ci_osx/2315/)
- Windows:
  - [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_windows&build=3000)](http://ci.ros2.org/job/ci_windows/3000/)

**Comment by mikaelarguedas** [comment]
@fmrico It looks like there is a typo that propagated throughout the entire patch: the new namespace is `rcutils` (the same as the name of the package) and not `rclutils`

**Comment by fmrico** [comment]
@mikaelarguedas I have pushed a new commit with this typo fixed.

**Comment by dirk-thomas** [comment]
- Linux:
  - [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux&build=2863)](http://ci.ros2.org/job/ci_linux/2863/)
- Linux-aarch64:
  - [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux-aarch64&build=367)](http://ci.ros2.org/job/ci_linux-aarch64/367/)
- macOS:
  - [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_osx&build=2318)](http://ci.ros2.org/job/ci_osx/2318/)
- Windows:
  - [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_windows&build=3003)](http://ci.ros2.org/job/ci_windows/3003/)

**Comment by mikaelarguedas** [comment]
Additional CI with the turtlebot repos (this includes https://github.com/ros2/navigation/issues/13)

- Linux:
  - [![Build Status](http://ci.ros2.org/buildStatus/icon?job=/ci_turtlebot-demo_linux&build=81)](http://ci.ros2.org/job//ci_turtlebot-demo_linux/81/)
- Linux-aarch64:
  - [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_turtlebot-demo_linux-aarch64&build=89)](http://ci.ros2.org/job/ci_turtlebot-demo_linux-aarch64/89/)

**Comment by mikaelarguedas** [comment]
looks like all CI passed, if there is no objection I'll merge this before the nightlies start. thanks @fmrico for the contribution and iterating on this with us!

**Comment by dirk-thomas** [comment]
:+1:

**Comment by mikaelarguedas** [comment]
I don't see any function in `rcutils` missing a namespace so I'm going to close this. If you see any feel free to comment here this issue can be reopened
