### ISSUE TITLE
ROS distro for conditional includes in C++

### ISSUE THREAD

**Issue by MaxFleur** [ros2/rcutils#479]
I am writing a user interface tool for various ROS2-related functionalities. This tool has been mainly written for ROS2 **Humble**. Now I want the tool to also run on ROS2 **Jazzy**.

The tool uses the ROS2-CV-Bridge. To include this in humble, the following line is needed in the header or cpp-file:
`#include <cv_bridge/cv_bridge.h>`
However, for Jazzy, this changed to
`#include <cv_bridge/cv_bridge.hpp>`.

To support the tool for both versions, imo the best option would be to include an `#ifdef` conditional include which roughly would look like this:
```
#ifdef ROS_HUMBLE
    #include <cv_bridge/cv_bridge.h>
#else
    #include <cv_bridge/cv_bridge.hpp>
#endif
```

However, I did not find any corresponding functionalities that ROS2 might offer. All I found was this post:
**https://answers.ros.org/question/336640/get-ros2-version-in-c/**

This post is five years old, however.
Has there been any development to call the ROS distro for usage in conditional includes? And if not, are there any alternatives for different header includes? Is it even possible to release such an application for different ROS distros?

**Comment by clalancette** [comment]
> However, I did not find any corresponding functionalities that ROS2 might offer. All I found was this post:
> **https://answers.ros.org/question/336640/get-ros2-version-in-c/**

That response is still valid, and what we generally recommend.  You can see this in use in for example https://github.com/ros-misc-utilities/ffmpeg_image_transport/blob/master/CMakeLists.txt .

Please open questions like this on https://robotics.stackexchange.com/questions/tagged/ros, which is our central Question and Answer site.  You'll get a better answer there, and it will be searchable for the future.

Make sure to include a lot of information on what platform you are using, which ROS distribution you are using, and the exact steps you took.
